repos:
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
    -   id: autoflake
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace  # убирает лишние пробелы
    -   id: end-of-file-fixer  # добавляет пустую строку в конце файла
