# Use root/example as user/password credentials
version: '3.1'

services:

  mydb:
    image: mysql
    container_name: mydb
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    restart: always
    environment:
      - MYSQL_DATABASE=${db_name}
      # So you don't have to use root, but you can if you like
      - MYSQL_USER=${db_user_login}
      # You can use whatever password you like
      - MYSQL_PASSWORD=${db_user_password}
      # Password for root access
      - MYSQL_ROOT_PASSWORD=${db_root_password}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data-example will be persisted
    volumes:
      - ./db_data:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - mydb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '80:80'
    environment:
      - PMA_HOST=${db_name}
      - MYSQL_ROOT_PASSWORD=${db_root_password}

  apache:
    image: httpd
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./public_html:/usr/local/apache2/htdocs/
  myapp7:
    depends_on:
      - mydb
    build: .
    links:
      - mydb
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    command:
      - python app/backend/db_create.py
      - python app/backend/data/script.py
      - cd app/backend
      - uvicorn main:app --reload
volumes:
  db_data:

