[tool.autoflake]
# return error code if changes are needed
check = false
# make changes to files instead of printing diffs
in-place = true
# drill down directories recursively
recursive = true
# remove all unused imports (not just those from the standard library)
remove-all-unused-imports = true

[tool.isort]
profile = "black"