name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: install lwp-request
      run: sudo apt install libwww-perl
    - name: Git clone
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    - name: Environments
      env:
          ENV_DATA: ${{ secrets.ENV_MARIADB }}
      run: |
          echo "$ENV_DATA" > .env
    - name: Build and deploy
      run: |
        docker-compose up -d -e db_host="localhost"
