name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Python install
      run: apt-get install python3.11 -y
    - name: Git clone
      uses: actions/checkout@v2
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    - name: Environments
      env:
          ENV_DATA: ${{ secrets.ENV_MARIADB }}
      run: |
          echo "$ENV_DATA" > .env
    - name: Build and deploy
      run: |
        docker-compose up -d
