name: "My GitHub Actions"
on:
  push:
    branches:
      - main
jobs:
  testing:
    runs-on: macos-latest
    steps: 
      - name: "Print hello testing"
        run: echo "hello, its testing"
  prod_deployment:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: "Print hello prod"
        run: echo "hello, its prod"
      - name: "Git clone"
        uses: actions/checkout@v1
      - name: "Print files in directory"
        run: ls -la
